# Generated by Django 5.1.6 on 2025-03-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Termek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('ar', models.IntegerField()),
                ('erzekenyseg', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Termék',
                'verbose_name_plural': 'Termékek',
            },
        ),
    ]
