# Generated by Django 5.1.6 on 2025-03-06 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_krisz_javit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendeles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('kartyae', models.BooleanField()),
                ('rendeles_ideje', models.DateTimeField()),
                ('elkeszult', models.BooleanField()),
                ('termek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_krisz_javit.termek')),
            ],
            options={
                'verbose_name': 'Rendelés',
                'verbose_name_plural': 'Rendelések',
            },
        ),
    ]
